import oaspec_support as support

pub fn parser_smoke_test() {
  let _ = support.parse_petstore_case()
  let _ = support.parse_petstore_has_paths_case()
  let _ = support.parse_petstore_has_components_case()
  let _ = support.parse_file_not_found_case()
  let _ = support.parse_json_string_minimal_spec_case()
  let _ = support.parse_json_string_preserves_required_array_order_case()
  let _ = support.parse_json_string_handles_many_paths_case()
  let _ = support.parse_json_string_rejects_malformed_case()
  let _ = support.parse_json_string_malformed_has_diagnostic_shape_case()
  let _ = support.parse_file_dispatches_json_path_for_json_extension_case()
  let _ = support.parse_json_string_preserves_yes_no_string_values_case()
  let _ = support.parse_json_string_preserves_dotted_version_literal_case()
  let _ = support.parser_rejects_duplicate_response_status_code_case()
  let _ = support.parser_rejects_response_status_below_100_case()
  let _ = support.parser_rejects_response_status_above_599_case()
  let _ = support.parser_rejects_response_status_zero_case()
  let _ = support.parser_rejects_response_status_negative_case()
  let _ = support.parser_rejects_response_status_leading_zero_case()
  let _ = support.parser_rejects_response_status_huge_int_case()
  let _ = support.parser_rejects_response_status_explicit_plus_case()
  let _ = support.parser_accepts_response_status_canonical_3_digit_case()
  let _ = support.parser_accepts_response_status_wildcards_case()
  let _ = support.parser_accepts_response_status_default_case()
  let _ = support.parser_rejects_yaml_int_response_status_below_100_case()
  let _ = support.parser_rejects_duplicate_components_response_name_case()
  let _ = support.parser_rejects_yaml_alias_without_anchor_case()
  let _ = support.parser_rejects_yaml_alias_with_no_matching_anchor_path_case()
  let _ =
    support.parse_string_with_limits_accepts_input_under_default_cap_case()
  let _ = support.parse_string_with_limits_rejects_input_over_byte_cap_case()
  let _ =
    support.parse_string_with_limits_default_limits_match_documented_caps_case()
  let _ = support.parse_json_string_with_locations_returns_same_spec_case()
  let _ = support.parse_json_string_with_locations_index_is_empty_case()
  let _ = support.parse_string_or_json_with_locations_routes_json_test_case()
  let _ = support.parse_string_or_json_with_locations_routes_yaml_test_case()
  let _ =
    support.parse_string_or_json_with_locations_array_root_routes_json_case()
  let _ = support.oss_oai_petstore_expanded_yaml_and_json_agree_case()
  let _ = support.oss_oai_petstore_expanded_yaml_path_count_pinned_case()
  let _ = support.oss_oai_webhook_example_yaml_and_json_agree_case()
  let _ = support.oss_oai_webhook_example_components_match_case()
}

pub fn openapi_version_gate_test() {
  let _ = support.parse_rejects_openapi_2_0_case()
  let _ = support.parse_rejects_openapi_4_0_0_case()
  let _ = support.parse_rejects_openapi_3_2_0_case()
  let _ = support.parse_rejects_malformed_patch_segment_case()
  let _ = support.parse_rejects_openapi_with_extra_segment_case()
  let _ = support.parse_rejects_bare_openapi_3_case()
  let _ = support.parse_accepts_openapi_3_0_3_case()
  let _ = support.parse_accepts_openapi_3_1_0_case()
  let _ = support.parse_rejects_unquoted_openapi_float_from_yaml_case()
  let _ = support.parse_accepts_quoted_openapi_3_0_from_yaml_case()
  let _ = support.parse_rejects_unquoted_openapi_int_from_yaml_case()
}

pub fn parser_security_and_shape_test() {
  let _ = support.parse_secure_api_has_security_schemes_case()
  let _ = support.parse_secure_api_operation_has_security_case()
  let _ = support.parse_accepts_basic_auth_case()
  let _ = support.parse_accepts_digest_auth_case()
  let _ = support.parse_rejects_malformed_security_scopes_case()
  let _ = support.parse_primitive_api_case()
  let _ = support.parse_global_security_inherited_case()
  let _ = support.ref_to_name_case()
  let _ = support.ref_to_name_simple_case()
  let _ = support.parse_parameter_style_deep_object_case()
  let _ = support.parse_parameter_style_none_case()
  let _ = support.parse_additional_properties_untyped_case()
  let _ = support.parse_absent_additional_properties_is_unspecified_case()
  let _ = support.parse_missing_responses_succeeds_with_empty_dict_case()
  let _ = support.parse_invalid_param_location_fails_case()
  let _ = support.parse_missing_openapi_field_fails_case()
  let _ = support.parse_missing_info_fails_case()
  let _ = support.parse_missing_info_title_fails_case()
  let _ = support.parse_json_oas_30_rejects_missing_paths_case()
  let _ = support.parse_json_rejects_integer_openapi_field_case()
  let _ = support.parse_json_rejects_paths_as_list_case()
  let _ = support.parse_json_oas_31_accepts_missing_paths_case()
  let _ = support.parse_rejects_optional_path_parameter_case()
  let _ = support.parse_accepts_oauth2_scheme_case()
  let _ = support.parse_accepts_apikey_cookie_case()
  let _ = support.parse_ignores_callbacks_case()
  let _ = support.openapi_31_anyof_with_null_branch_parses_case()
  let _ = support.openapi_31_oneof_with_null_branch_parses_case()
  let _ = support.openapi_31_standalone_null_type_parses_as_nullable_case()
  let _ = support.openapi_31_type_array_nullable_case()
  let _ = support.parser_rejects_request_body_missing_content_case()
  let _ = support.parser_rejects_response_missing_description_case()
  let _ = support.unrecognized_schema_type_rejected_case()
}

pub fn parser_lossless_ast_test() {
  let _ = support.parameter_style_is_adt_case()
  let _ = support.schema_metadata_lossless_case()
  let _ = support.security_scheme_in_is_adt_case()
  let _ = support.lossless_info_fields_case()
  let _ = support.lossless_server_variables_case()
  let _ = support.lossless_response_headers_links_case()
  let _ = support.lossless_tags_and_external_docs_case()
  let _ = support.parse_error_missing_info_has_actionable_message_case()
  let _ = support.parse_error_missing_version_has_path_case()
  let _ = support.parse_error_missing_param_name_has_path_case()
}

pub fn fixture_parse_smoke_test() {
  let _ = support.parse_wildcard_status_codes_case()
  let _ = support.parse_server_variables_case()
  let _ = support.parse_operation_server_override_case()
  let _ = support.parse_no_servers_case()
  let _ = support.parse_format_types_case()
  let _ = support.parse_dot_property_names_case()
  let _ = support.parse_inline_nested_objects_case()
  let _ = support.parse_array_param_styles_case()
  let _ = support.parse_delimited_param_styles_case()
  let _ = support.parse_empty_response_body_case()
  let _ = support.parse_enum_edge_cases_case()
  let _ = support.parse_multiple_response_content_case()
  let _ = support.parse_hyphen_property_names_case()
  let _ = support.parse_mixed_param_locations_case()
  let _ = support.parse_readonly_writeonly_properties_case()
  let _ = support.parse_complex_discriminator_case()
  let _ = support.parse_recursive_anyof_schema_case()
  let _ = support.parse_all_component_types_case()
  let _ = support.parse_default_response_only_case()
  let _ = support.parse_abbreviation_identifiers_case()
  let _ = support.parse_optional_required_combinations_case()
  let _ = support.schema_no_type_with_properties_parses_case()
}

pub fn parser_error_regression_test() {
  let _ = support.error_missing_openapi_field_case()
  let _ = support.error_swagger_v2_rejected_case()
  let _ = support.error_missing_info_case()
  let _ = support.error_missing_info_title_case()
  let _ = support.error_missing_info_version_case()
  let _ = support.error_empty_spec_case()
  let _ = support.error_invalid_json_as_yaml_parsed_but_may_fail_case()
  let _ = support.error_duplicate_operation_id_parses_case()
  let _ = support.error_missing_path_param_case()
  let _ = support.error_response_no_description_case()
}
