import oaspec_support as support

pub fn codegen_core_regressions_test() {
  let _ = support.allof_with_primitive_sub_schema_case()
  let _ = support.allof_part_types_not_in_generated_types_case()
  let _ = support.allof_part_types_not_in_generated_decoders_case()
  let _ = support.empty_object_decoder_omits_constructor_parens_case()
  let _ = support.encoder_for_empty_object_omits_unused_value_param_case()
  let _ = support.encoder_for_non_empty_object_keeps_value_param_case()
  let _ =
    support.synthetic_list_decoder_disambiguates_against_dashed_list_sibling_case()
  let _ =
    support.array_of_inline_string_enum_uses_plain_decoder_and_encoder_case()
  let _ = support.allof_part_types_not_in_generated_encoders_case()
  let _ = support.generation_is_idempotent_case()
  let _ = support.generated_type_fields_are_alphabetically_ordered_case()
  let _ = support.client_emits_with_request_wrappers_case()
  let _ = support.middleware_gleam_is_not_emitted_case()
  let _ = support.callbacks_do_not_emit_handler_stubs_case()
  let _ = support.client_uses_transport_send_contract_case()
  let _ = support.encode_dynamic_fallback_emits_null_case()
  let _ = support.client_emits_unexpected_status_variant_case()
  let _ = support.enum_decoder_failure_includes_rejected_value_case()
  let _ = support.client_query_params_preserve_declared_order_case()
  let _ = support.unknown_http_security_scheme_accepted_case()
  let _ = support.multiple_content_types_response_case()
  let _ = support.form_urlencoded_imports_case()
  let _ = support.callback_multiple_url_expressions_case()
  let _ = support.multi_content_response_type_safety_case()
  let _ = support.multi_content_request_body_case()
  let _ = support.security_or_alternatives_case()
  let _ = support.array_alias_decoder_encoder_case()
  let _ = support.bug1_optional_deep_object_array_leaf_case()
  let _ = support.bug2_form_urlencoded_ref_array_property_case()
  let _ = support.bug3_ref_array_query_param_import_case()
  let _ = support.deep_object_array_leaf_case()
  let _ = support.form_urlencoded_nested_object_case()
  let _ = support.form_urlencoded_two_level_nested_object_case()
  let _ = support.form_urlencoded_object_with_primitive_array_case()
  let _ = support.form_urlencoded_object_array_of_object_case()
  let _ = support.form_urlencoded_encoding_contenttype_json_case()
  let _ = support.form_urlencoded_composite_field_case()
  let _ = support.query_array_of_objects_emits_json_escape_case()
  let _ = support.deep_object_composite_property_emits_json_escape_case()
  let _ = support.head_operation_not_silently_dropped_case()
  let _ = support.options_operation_not_silently_dropped_case()
  let _ = support.optional_request_body_case()
  let _ = support.query_array_explode_true_case()
  let _ = support.oauth2_flows_preserved_case()
  let _ = support.server_handler_stubs_use_panic_not_todo_case()
  let _ = support.server_router_calls_handlers_case()
  let _ = support.generated_file_has_target_kind_case()
  let _ = support.response_code_range_2xx_generates_valid_gleam_case()
  let _ = support.status_code_range_pattern_case()
  let _ = support.status_code_suffix_range_case()
  let _ = support.status_code_suffix_full_iana_registry_case()
  let _ = support.anyof_generates_union_type_not_string_case()
  let _ = support.security_scopes_appear_as_comments_case()
  let _ = support.allow_reserved_skips_percent_encode_case()
  let _ = support.default_query_param_emits_raw_tuple_case()
  let _ = support.anyof_generates_record_with_option_fields_case()
  let _ = support.oneof_still_generates_tagged_union_case()
  let _ = support.request_body_encoding_warning_is_surfaced_case()
}

pub fn guard_and_decoder_generation_test() {
  let _ = support.validate_constraints_generate_guards_case()
  let _ = support.validate_constraints_emit_structured_failures_case()
  let _ = support.guards_minlength_one_uses_singular_character_case()
  let _ = support.guards_minmax_length_plural_above_one_case()
  let _ = support.validate_top_level_string_pattern_generates_guard_case()
  let _ =
    support.validate_object_property_count_still_collects_nested_string_constraints_case()
  let _ = support.typed_additional_props_decoder_uses_dynamic_case()
  let _ =
    support.typed_additional_props_decoder_rejects_invalid_extra_values_case()
  let _ = support.multipart_optional_field_generates_case_expr_case()
  let _ = support.multipart_ref_scalar_field_is_stringified_case()
  let _ = support.path_ref_array_parameters_are_stringified_case()
  let _ = support.guards_composite_validator_compiles_case()
  let _ = support.guards_optional_field_and_array_suffix_case()
  let _ = support.guards_exclusive_and_multiple_of_integer_case()
  let _ = support.guards_exclusive_and_multiple_of_float_case()
  let _ = support.guards_top_level_integer_exclusive_and_multiple_of_case()
  let _ = support.guards_unique_items_generates_guard_case()
  let _ = support.guards_unique_items_field_generates_guard_case()
  let _ = support.guards_min_properties_generates_guard_case()
  let _ = support.guards_enum_edge_cases_case()
  let _ = support.guards_format_types_case()
  let _ = support.allof_validators_dedup_across_children_case()
}

pub fn schema_dispatch_and_ir_render_test() {
  let _ = support.schema_dispatch_primitive_types_case()
  let _ = support.schema_dispatch_to_string_expr_case()
  let _ = support.ir_render_type_alias_case()
  let _ = support.ir_render_union_type_case()
  let _ = support.ir_render_record_type_case()
  let _ = support.ir_build_inline_nested_objects_case()
  let _ = support.ir_build_abbreviation_identifiers_case()
}

pub fn decoder_semantics_test() {
  let _ =
    support.additional_properties_untyped_encoder_includes_extra_props_case()
  let _ = support.anyof_discriminator_preserved_case()
  let _ = support.oneof_no_discriminator_ref_decoder_case()
  let _ = support.nullable_primitive_decoder_encoder_case()
  let _ = support.nullable_oneof_generates_option_type_case()
  let _ = support.top_level_array_response_uses_json_array_case()
  let _ = support.validate_decode_list_collision_auto_disambiguates_case()
  let _ =
    support.validate_inline_enum_component_collision_auto_disambiguates_case()
  let _ = support.validate_stripe_dotted_schema_no_longer_collides_case()
  let _ = support.additional_properties_false_emits_unknown_key_check_case()
  let _ = support.oneof_decoder_rejects_multi_branch_matches_case()
  let _ =
    support.additional_properties_false_via_allof_emits_unknown_key_check_case()
}

pub fn server_variable_and_readonly_codegen_test() {
  let _ = support.read_only_filtered_from_request_body_type_case()
  let _ = support.read_only_filtered_from_encoder_case()
  let _ = support.write_only_filtered_from_response_decoder_case()
  let _ = support.read_only_filtered_from_component_encoder_with_hoist_case()
  let _ = support.server_variable_substitution_default_base_url_case()
  let _ = support.server_no_variables_default_base_url_case()
  let _ = support.server_empty_default_base_url_case()
}

pub fn feature_fixture_codegen_smoke_test() {
  let _ = support.generate_wildcard_status_codes_case()
  let _ = support.generate_server_variables_produces_types_case()
  let _ = support.generate_format_types_case()
  let _ = support.generate_dot_property_names_produces_valid_identifiers_case()
  let _ = support.generate_inline_nested_objects_case()
  let _ = support.generate_enum_edge_cases_case()
  let _ = support.generate_hyphen_property_names_valid_gleam_case()
  let _ = support.generate_mixed_param_locations_case()
  let _ = support.generate_complex_discriminator_case()
  let _ = support.generate_recursive_anyof_schema_types_case()
  let _ = support.required_self_ref_currently_accepted_case()
  let _ = support.generate_default_response_only_case()
  let _ = support.generate_abbreviation_identifiers_valid_gleam_case()
  let _ = support.generate_optional_required_combinations_case()
  let _ = support.generate_readonly_writeonly_filters_case()
  let _ = support.generate_all_component_types_case()
  let _ = support.generate_array_param_styles_server_case()
  let _ = support.generate_delimited_param_styles_client_case()
  let _ = support.generate_delimited_param_styles_server_case()
  let _ = support.generate_empty_response_body_server_case()
  let _ = support.generate_multiple_response_content_client_case()
  let _ = support.decoders_wildcard_status_codes_case()
  let _ = support.decoders_complex_discriminator_case()
  let _ = support.decoders_enum_edge_cases_case()
  let _ = support.decoders_format_types_case()
  let _ = support.decoders_recursive_anyof_case()
}

pub fn compile_and_e2e_smoke_test() {
  let _ = support.compile_wildcard_responses_full_pipeline_case()
  let _ = support.compile_format_types_full_pipeline_case()
  let _ = support.compile_mixed_params_full_pipeline_case()
  let _ = support.compile_enum_variants_full_pipeline_case()
  let _ = support.e2e_wildcard_status_codes_case()
  let _ = support.e2e_format_types_case()
  let _ = support.e2e_complex_discriminator_case()
  let _ = support.e2e_enum_edge_cases_case()
  let _ = support.e2e_mixed_param_locations_case()
  let _ = support.e2e_inline_nested_objects_case()
  let _ = support.e2e_optional_required_combinations_case()
  let _ = support.e2e_no_servers_case()
}
