import oaspec_support as support

pub fn parser_smoke_test() {
  let _ = support.parse_petstore_case()
  let _ = support.parse_petstore_has_paths_case()
  let _ = support.parse_petstore_has_components_case()
  let _ = support.parse_file_not_found_case()
  let _ = support.parse_json_string_minimal_spec_case()
  let _ = support.parse_json_string_preserves_required_array_order_case()
  let _ = support.parse_json_string_handles_many_paths_case()
  let _ = support.parse_json_string_rejects_malformed_case()
  let _ = support.parse_json_string_malformed_has_diagnostic_shape_case()
  let _ = support.parse_file_dispatches_json_path_for_json_extension_case()
  let _ = support.oss_oai_petstore_expanded_yaml_and_json_agree_case()
  let _ = support.oss_oai_petstore_expanded_yaml_path_count_pinned_case()
  let _ = support.oss_oai_webhook_example_yaml_and_json_agree_case()
  let _ = support.oss_oai_webhook_example_components_match_case()
}

pub fn openapi_version_gate_test() {
  let _ = support.parse_rejects_openapi_2_0_case()
  let _ = support.parse_rejects_openapi_4_0_0_case()
  let _ = support.parse_rejects_openapi_3_2_0_case()
  let _ = support.parse_rejects_malformed_patch_segment_case()
  let _ = support.parse_rejects_openapi_with_extra_segment_case()
  let _ = support.parse_rejects_bare_openapi_3_case()
  let _ = support.parse_accepts_openapi_3_0_3_case()
  let _ = support.parse_accepts_openapi_3_1_0_case()
  let _ = support.parse_accepts_openapi_3_0_from_yaml_float_case()
}

pub fn parser_security_and_shape_test() {
  let _ = support.parse_secure_api_has_security_schemes_case()
  let _ = support.parse_secure_api_operation_has_security_case()
  let _ = support.parse_accepts_basic_auth_case()
  let _ = support.parse_accepts_digest_auth_case()
  let _ = support.parse_rejects_malformed_security_scopes_case()
  let _ = support.parse_primitive_api_case()
  let _ = support.parse_global_security_inherited_case()
  let _ = support.ref_to_name_case()
  let _ = support.ref_to_name_simple_case()
  let _ = support.parse_parameter_style_deep_object_case()
  let _ = support.parse_parameter_style_none_case()
  let _ = support.parse_additional_properties_untyped_case()
  let _ = support.parse_absent_additional_properties_is_unspecified_case()
  let _ = support.parse_missing_responses_succeeds_with_empty_dict_case()
  let _ = support.parse_invalid_param_location_fails_case()
  let _ = support.parse_missing_openapi_field_fails_case()
  let _ = support.parse_missing_info_fails_case()
  let _ = support.parse_missing_info_title_fails_case()
  let _ = support.parse_rejects_optional_path_parameter_case()
  let _ = support.parse_accepts_oauth2_scheme_case()
  let _ = support.parse_accepts_apikey_cookie_case()
  let _ = support.parse_ignores_callbacks_case()
  let _ = support.openapi_31_anyof_with_null_branch_parses_case()
  let _ = support.openapi_31_oneof_with_null_branch_parses_case()
  let _ = support.openapi_31_standalone_null_type_parses_as_nullable_case()
  let _ = support.openapi_31_type_array_nullable_case()
  let _ = support.parser_rejects_request_body_missing_content_case()
  let _ = support.parser_rejects_response_missing_description_case()
  let _ = support.unrecognized_schema_type_rejected_case()
}

pub fn parser_lossless_ast_test() {
  let _ = support.parameter_style_is_adt_case()
  let _ = support.schema_metadata_lossless_case()
  let _ = support.security_scheme_in_is_adt_case()
  let _ = support.lossless_info_fields_case()
  let _ = support.lossless_server_variables_case()
  let _ = support.lossless_response_headers_links_case()
  let _ = support.lossless_tags_and_external_docs_case()
  let _ = support.parse_error_missing_info_has_actionable_message_case()
  let _ = support.parse_error_missing_version_has_path_case()
  let _ = support.parse_error_missing_param_name_has_path_case()
}

pub fn fixture_parse_smoke_test() {
  let _ = support.parse_wildcard_status_codes_case()
  let _ = support.parse_server_variables_case()
  let _ = support.parse_operation_server_override_case()
  let _ = support.parse_no_servers_case()
  let _ = support.parse_format_types_case()
  let _ = support.parse_dot_property_names_case()
  let _ = support.parse_inline_nested_objects_case()
  let _ = support.parse_array_param_styles_case()
  let _ = support.parse_delimited_param_styles_case()
  let _ = support.parse_empty_response_body_case()
  let _ = support.parse_enum_edge_cases_case()
  let _ = support.parse_multiple_response_content_case()
  let _ = support.parse_hyphen_property_names_case()
  let _ = support.parse_mixed_param_locations_case()
  let _ = support.parse_readonly_writeonly_properties_case()
  let _ = support.parse_complex_discriminator_case()
  let _ = support.parse_recursive_anyof_schema_case()
  let _ = support.parse_all_component_types_case()
  let _ = support.parse_default_response_only_case()
  let _ = support.parse_abbreviation_identifiers_case()
  let _ = support.parse_optional_required_combinations_case()
  let _ = support.schema_no_type_with_properties_parses_case()
}

pub fn parser_error_regression_test() {
  let _ = support.error_missing_openapi_field_case()
  let _ = support.error_swagger_v2_rejected_case()
  let _ = support.error_missing_info_case()
  let _ = support.error_missing_info_title_case()
  let _ = support.error_missing_info_version_case()
  let _ = support.error_empty_spec_case()
  let _ = support.error_invalid_json_as_yaml_parsed_but_may_fail_case()
  let _ = support.error_duplicate_operation_id_parses_case()
  let _ = support.error_missing_path_param_case()
  let _ = support.error_response_no_description_case()
}
