#!/usr/bin/env bash
#
# Generate-and-build the full GitHub OpenAPI document end-to-end.
# Catches the class of bugs that surface only on real-world specs of
# this size (~10k component schemas, ~1k operations) — hangs in
# import-needs analysis, name collisions, broken type-shape
# assumptions in the validator codegen.
#
# Steps:
#   1. Download the GitHub OpenAPI yaml (cached under /tmp, refreshed
#      weekly). A failed download is a soft skip on the assumption
#      contributors may be offline.
#   2. Run `oaspec generate` with `validate: true` so every codegen
#      module is exercised end-to-end.
#   3. Verify the generated files are formatted and carry the codegen
#      provenance header.
#   4. Build the generated package with `--warnings-as-errors`.
#
# Glinter is intentionally NOT run against the generated full-GitHub
# package. Its analysis is quadratic in module size, so on the spec's
# 30k+-line decode/encode/guard modules it adds another multi-minute
# pass that materially slows CI for diminishing return — every rule
# the linter would surface also surfaces against the project's own
# sources via the linter step in the main CI job.
#
# Set `OASPEC_SKIP_GITHUB_TEST=1` to skip everything (offline runs).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

info() {
  echo "==> $*"
}

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

# Same shape as `integration_test/run.sh::verify_generated_format`,
# duplicated here so this script can run as a standalone CI job
# without sourcing the larger runner.
verify_generated_format() {
  local target_dir="$1"
  if [ ! -d "$target_dir" ]; then
    return 0
  fi
  local files
  files=$(find "$target_dir" -name '*.gleam' ! -name 'handlers.gleam')
  if [ -z "$files" ]; then
    return 0
  fi

  # A zero-length generated file slips past `gleam build
  # --warnings-as-errors` with only an "empty module" warning, so we
  # catch template-renderer regressions here instead.
  while IFS= read -r f; do
    if [ ! -s "$f" ]; then
      fail "Generated file $f is empty (codegen regression)."
    fi
  done <<< "$files"

  # Every generated file must carry the codegen provenance header,
  # otherwise we assume the file did not flow through `oaspec
  # generate`.
  while IFS= read -r f; do
    if ! head -n1 "$f" | grep -q "// Code generated by oaspec"; then
      fail "Generated file $f is missing the codegen provenance header."
    fi
  done <<< "$files"

  # `oaspec generate` runs `gleam format` during emission, so a
  # no-op `gleam format --check` must succeed. A formatter regression
  # surfaces here even when the build still passes.
  # shellcheck disable=SC2086 -- intentional word-splitting on find output
  gleam format --check $files \
    || fail "Generated code under $target_dir is not gleam-formatted."
}

if [ "${OASPEC_SKIP_GITHUB_TEST:-0}" = "1" ]; then
  info "OASPEC_SKIP_GITHUB_TEST=1 — skipping full GitHub OpenAPI test."
  exit 0
fi

info "Full GitHub OpenAPI generation + format + build test..."

GITHUB_API_CACHE="${OASPEC_GITHUB_API_CACHE:-/tmp/oaspec_github_api.yaml}"
GITHUB_API_URL="https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml"

# Refresh the cache when missing OR older than 7 days.
needs_download=0
if [ ! -f "$GITHUB_API_CACHE" ]; then
  needs_download=1
elif [ -n "$(find "$GITHUB_API_CACHE" -mtime +7 -print 2>/dev/null)" ]; then
  needs_download=1
fi

if [ "$needs_download" = "1" ]; then
  info "Downloading GitHub OpenAPI to $GITHUB_API_CACHE ..."
  if ! curl -fsSL --max-time 120 -o "$GITHUB_API_CACHE.tmp" "$GITHUB_API_URL"; then
    rm -f "$GITHUB_API_CACHE.tmp"
    info "WARNING: download failed (network or rate limit)."
    info "Skipping full GitHub OpenAPI test."
    info "(Set OASPEC_SKIP_GITHUB_TEST=1 to silence this notice.)"
    exit 0
  fi
  mv "$GITHUB_API_CACHE.tmp" "$GITHUB_API_CACHE"
fi

GITHUB_TEST_DIR="$SCRIPT_DIR/github_full_test"
rm -rf "$GITHUB_TEST_DIR"
mkdir -p "$GITHUB_TEST_DIR/src"

cat > "$GITHUB_TEST_DIR/oaspec.yaml" << YAML_EOF
input: $GITHUB_API_CACHE
mode: client
validate: true

targets:
  - package: github_full_test
    output:
      dir: ./integration_test/github_full_test/src
YAML_EOF

cat > "$GITHUB_TEST_DIR/gleam.toml" << 'TOML_EOF'
name = "github_full_test"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
oaspec = { path = "../.." }
TOML_EOF

cat > "$GITHUB_TEST_DIR/src/github_full_test.gleam" << 'GLEAM_EOF'
pub fn main() {
  Nil
}
GLEAM_EOF

cd "$PROJECT_ROOT"
info "Generating (this typically takes ~50s)..."
gleam run -- generate --config="$GITHUB_TEST_DIR/oaspec.yaml" \
  || fail "\`oaspec generate\` failed on full GitHub OpenAPI."

verify_generated_format integration_test/github_full_test/src/github_full_test

cd "$GITHUB_TEST_DIR"
gleam deps download

info "Compiling generated client (warnings-as-errors) ..."
gleam build --warnings-as-errors \
  || fail "Generated full-GitHub client failed to compile."
info "PASS: generated client compiles cleanly."

cd "$PROJECT_ROOT"
rm -rf "$GITHUB_TEST_DIR"
info "Full GitHub OpenAPI integration test passed."
