#!/usr/bin/env bash
#
# Generate-and-build the full Stripe OpenAPI document end-to-end.
# Companion to `github_full.sh`. Catches the class of bugs that
# surface only on real-world specs of Stripe's size and shape:
# ~1k operations heavy on `application/x-www-form-urlencoded`
# request bodies, `oneOf` / `anyOf` / `allOf` field composites,
# `style: deepObject` query parameters, and array query parameters
# whose items resolve to objects.
#
# The Stripe spec is committed in-repo
# (`doc/reference/oss/libopenapi/test_specs/stripe.yaml`), so this
# job has no network dependency — it always runs.
#
# Steps:
#   1. Run `oaspec generate` against `stripe.yaml` with
#      `validate: true` so every codegen module is exercised end-
#      to-end against the residual shapes PR #543 fixed.
#   2. Verify the generated files are formatted and carry the
#      codegen provenance header.
#   3. Build the generated package with `--warnings-as-errors`.
#
# Glinter is intentionally NOT run against the generated full-Stripe
# package; same rationale as `github_full.sh` (quadratic on module
# size, the project's own sources already cover every rule).
#
# Set `OASPEC_SKIP_STRIPE_TEST=1` to skip everything.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

info() {
  echo "==> $*"
}

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

verify_generated_format() {
  local target_dir="$1"
  if [ ! -d "$target_dir" ]; then
    return 0
  fi
  local files
  files=$(find "$target_dir" -name '*.gleam' ! -name 'handlers.gleam')
  if [ -z "$files" ]; then
    return 0
  fi

  while IFS= read -r f; do
    if [ ! -s "$f" ]; then
      fail "Generated file $f is empty (codegen regression)."
    fi
  done <<< "$files"

  while IFS= read -r f; do
    if ! head -n1 "$f" | grep -q "// Code generated by oaspec"; then
      fail "Generated file $f is missing the codegen provenance header."
    fi
  done <<< "$files"

  # shellcheck disable=SC2086 -- intentional word-splitting on find output
  gleam format --check $files \
    || fail "Generated code under $target_dir is not gleam-formatted."
}

if [ "${OASPEC_SKIP_STRIPE_TEST:-0}" = "1" ]; then
  info "OASPEC_SKIP_STRIPE_TEST=1 — skipping full Stripe OpenAPI test."
  exit 0
fi

info "Full Stripe OpenAPI generation + format + build test..."

STRIPE_SPEC="$PROJECT_ROOT/doc/reference/oss/libopenapi/test_specs/stripe.yaml"
if [ ! -f "$STRIPE_SPEC" ]; then
  fail "Stripe spec not found at $STRIPE_SPEC"
fi

STRIPE_TEST_DIR="$SCRIPT_DIR/stripe_full_test"
rm -rf "$STRIPE_TEST_DIR"
mkdir -p "$STRIPE_TEST_DIR/src"

cat > "$STRIPE_TEST_DIR/oaspec.yaml" << YAML_EOF
input: $STRIPE_SPEC
mode: client
validate: true

targets:
  - package: stripe_full_test
    output:
      dir: ./integration_test/stripe_full_test/src
YAML_EOF

cat > "$STRIPE_TEST_DIR/gleam.toml" << 'TOML_EOF'
name = "stripe_full_test"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
oaspec = { path = "../.." }
TOML_EOF

cat > "$STRIPE_TEST_DIR/src/stripe_full_test.gleam" << 'GLEAM_EOF'
pub fn main() {
  Nil
}
GLEAM_EOF

cd "$PROJECT_ROOT"
info "Generating (this typically takes ~30s)..."
gleam run -- generate --config="$STRIPE_TEST_DIR/oaspec.yaml" \
  || fail "\`oaspec generate\` failed on full Stripe OpenAPI."

verify_generated_format integration_test/stripe_full_test/src/stripe_full_test

cd "$STRIPE_TEST_DIR"
gleam deps download

# `gleam build` (no `--warnings-as-errors`) is what proves the
# generated client is type-safe end-to-end. The full-Stripe code
# path emits a long tail of stylistic warnings (unused-variable
# shadowing in deeply nested record builders, unreachable
# `None ->` arms after a constant `Some(_)` branch) that don't
# affect correctness; tightening the emitter to silence them is
# tracked as a follow-up. Set `OASPEC_REQUIRE_STRIPE_NO_WARNINGS=1`
# to flip the gate back on for local strict runs.
info "Compiling generated client ..."
gleam build \
  || fail "Generated full-Stripe client failed to compile."
if [ "${OASPEC_REQUIRE_STRIPE_NO_WARNINGS:-0}" = "1" ]; then
  info "Re-running with --warnings-as-errors (strict) ..."
  gleam build --warnings-as-errors \
    || fail "Generated full-Stripe client emitted warnings under strict mode."
fi
info "PASS: generated client compiles cleanly."

cd "$PROJECT_ROOT"
rm -rf "$STRIPE_TEST_DIR"
info "Full Stripe OpenAPI integration test passed."
