#!/bin/sh
# shellcheck shell=sh

# Integration tests for oaspec code generation.
# Uses a single generation run for file/content checks to keep tests fast.

Describe 'oaspec top-level help'
  Include "$SHELLSPEC_SPECDIR/spec_helper.sh"

  It 'lists available subcommands when called with --help'
    When run oaspec_cli --help
    The status should be success
    The output should include 'Commands:'
    The output should include 'init'
    The output should include 'generate'
    The output should include 'validate'
  End

  Describe 'colour output'
    # shellspec captures stdout via a pipe, so the CLI sees stdout as
    # non-TTY. Both checks together cover the two suppression paths
    # (TTY check and NO_COLOR honour).
    It 'omits ANSI escape sequences when stdout is not a TTY'
      When run oaspec_cli --help
      The status should be success
      The output should not include "$(printf '\033[')"
    End

    It 'omits ANSI escape sequences when NO_COLOR is set'
      export NO_COLOR=1
      When run oaspec_cli --help
      The status should be success
      The output should not include "$(printf '\033[')"
    End
  End
End

Describe 'oaspec generate'
  Include "$SHELLSPEC_SPECDIR/spec_helper.sh"

  # -------------------------------------------------------------------
  # Basic CLI behaviour (these need to actually run the CLI)
  # -------------------------------------------------------------------

  Describe 'CLI help'
    It 'shows usage when called with --help'
      When run generate --help
      The status should be success
      The output should include 'generate'
      The output should include 'config'
    End
  End

  Describe 'error handling'
    It 'exits with error when config file does not exist'
      When run generate --config=nonexistent.yaml
      The status should be failure
      The output should include 'Error'
    End
  End

  Describe 'successful generation'
    It 'exits successfully and reports file count'
      clean_test_output
      When run generate --config=test/fixtures/oaspec.yaml
      The status should be success
      The output should include 'Successfully generated'
      The output should include '15 files'
    End
  End

  # -------------------------------------------------------------------
  # File existence checks (generate once, check many)
  # -------------------------------------------------------------------

  Describe 'generated files'
    BeforeAll 'clean_test_output'
    BeforeAll 'generate_petstore_once'
    AfterAll 'clean_test_output'

    # --- Server files ---

    It 'creates server/types.gleam'
      The path "$TEST_OUTPUT_DIR/api/types.gleam" should be file
    End

    It 'creates server/request_types.gleam'
      The path "$TEST_OUTPUT_DIR/api/request_types.gleam" should be file
    End

    It 'creates server/response_types.gleam'
      The path "$TEST_OUTPUT_DIR/api/response_types.gleam" should be file
    End

    It 'creates server/decode.gleam'
      The path "$TEST_OUTPUT_DIR/api/decode.gleam" should be file
    End

    It 'creates server/encode.gleam'
      The path "$TEST_OUTPUT_DIR/api/encode.gleam" should be file
    End

    It 'creates server/handlers.gleam'
      The path "$TEST_OUTPUT_DIR/api/handlers.gleam" should be file
    End

    It 'creates server/router.gleam'
      The path "$TEST_OUTPUT_DIR/api/router.gleam" should be file
    End

    # --- Client files ---

    It 'creates client/types.gleam'
      The path "$TEST_OUTPUT_DIR_CLIENT/api/types.gleam" should be file
    End

    It 'creates client/client.gleam'
      The path "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should be file
    End
  End

  # -------------------------------------------------------------------
  # Generated code content verification (reuses the same output)
  # -------------------------------------------------------------------

  Describe 'generated code content'
    BeforeAll 'generate_petstore_once'

    # --- File header ---

    It 'types.gleam has auto-generation header'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'Code generated by oaspec'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'DO NOT EDIT'
    End

    # --- Types ---

    It 'generates Pet type with correct fields'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type Pet {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'id: Int'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'name: String'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'status: PetStatus'
    End

    It 'generates PetStatus enum variants'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type PetStatus {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'PetStatusAvailable'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'PetStatusPending'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'PetStatusSold'
    End

    It 'generates CreatePetRequest type'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type CreatePetRequest {'
    End

    It 'generates Error type'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type Error {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'code: Int'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'message: String'
    End

    It 'marks optional fields with Option type'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'tag: Option(String)'
    End

    # --- OpenAPI description propagation ---

    It 'propagates schema descriptions as doc comments'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include '/// A pet in the store'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include '/// The status of a pet in the store'
    End

    # --- Request types ---

    It 'generates ListPetsRequest with query parameters'
      The contents of file "$TEST_OUTPUT_DIR/api/request_types.gleam" should include 'pub type ListPetsRequest {'
      The contents of file "$TEST_OUTPUT_DIR/api/request_types.gleam" should include 'limit: Option(Int)'
      The contents of file "$TEST_OUTPUT_DIR/api/request_types.gleam" should include 'offset: Option(Int)'
    End

    It 'generates GetPetRequest with path parameter'
      The contents of file "$TEST_OUTPUT_DIR/api/request_types.gleam" should include 'pub type GetPetRequest {'
      The contents of file "$TEST_OUTPUT_DIR/api/request_types.gleam" should include 'pet_id: Int'
    End

    # --- Response types ---

    It 'generates response types with status code variants'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'pub type ListPetsResponse {'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'ResponseOk'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'ResponseUnauthorized'
    End

    It 'generates CreatePetResponse with Created and BadRequest variants'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'pub type CreatePetResponse {'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'ResponseCreated'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'ResponseBadRequest'
    End

    It 'generates DeletePetResponse with NoContent variant'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'ResponseNoContent'
    End

    # --- Decoders ---

    It 'generates decoder functions using gleam/dynamic/decode'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include 'import gleam/dynamic/decode'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include 'pub fn decode_pet'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include 'decode.field'
    End

    It 'generates enum decoder with pattern matching'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include 'pub fn decode_pet_status'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include '"available"'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include '"pending"'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include '"sold"'
    End

    It 'enum decoder rejects unknown values with decode.failure'
      The contents of file "$TEST_OUTPUT_DIR/api/decode.gleam" should include 'decode.failure'
    End

    # --- Encoders ---

    It 'generates encoder functions with _json and String variants'
      The contents of file "$TEST_OUTPUT_DIR/api/encode.gleam" should include 'import gleam/json'
      The contents of file "$TEST_OUTPUT_DIR/api/encode.gleam" should include 'pub fn encode_pet_json'
      The contents of file "$TEST_OUTPUT_DIR/api/encode.gleam" should include 'pub fn encode_pet('
      The contents of file "$TEST_OUTPUT_DIR/api/encode.gleam" should include 'json.object'
    End

    It 'ref encoder uses _json function not json.string wrapper'
      The contents of file "$TEST_OUTPUT_DIR/api/encode.gleam" should include 'encode_pet_status_json(value.status)'
    End

    # --- Server handlers ---

    It 'generates handler stubs with panic placeholders'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'pub fn list_pets'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'pub fn create_pet'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'pub fn get_pet'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'pub fn delete_pet'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'panic as "unimplemented:'
    End

    It 'handler signatures reference request and response types'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'import api/request_types'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'import api/response_types'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'request_types.ListPetsRequest'
      The contents of file "$TEST_OUTPUT_DIR/api/handlers.gleam" should include 'response_types.ListPetsResponse'
    End

    # --- Router ---

    It 'generates router with path matching'
      The contents of file "$TEST_OUTPUT_DIR/api/router.gleam" should include 'pub fn route'
      The contents of file "$TEST_OUTPUT_DIR/api/router.gleam" should include '"GET"'
      The contents of file "$TEST_OUTPUT_DIR/api/router.gleam" should include '"POST"'
      The contents of file "$TEST_OUTPUT_DIR/api/router.gleam" should include '"DELETE"'
    End

    # --- Client ---

    It 'generates client functions for each operation'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'pub fn list_pets'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'pub fn create_pet'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'pub fn get_pet'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'pub fn delete_pet'
    End

    It 'client uses http request construction'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'import gleam/http/request'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'request.to'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'request.set_method'
    End

    It 'client has ClientConfig type'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'pub type ClientConfig {'
      The contents of file "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should include 'pub fn new'
    End

    # --- Middleware ---

    # middleware.gleam is intentionally no longer emitted (see issue #116).
  End

  # -------------------------------------------------------------------
  # Mode-specific generation
  # -------------------------------------------------------------------

  Describe 'mode=server'
    It 'generates only server files'
      clean_test_output
      When run generate --config=test/fixtures/oaspec.yaml --mode=server
      The status should be success
      The output should include 'Successfully generated'
      The path "$TEST_OUTPUT_DIR/api/handlers.gleam" should be file
      The path "$TEST_OUTPUT_DIR/api/router.gleam" should be file
      The path "$TEST_OUTPUT_DIR_CLIENT/api" should not be exist
    End
  End

  Describe 'mode=client'
    It 'generates only client files'
      clean_test_output
      When run generate --config=test/fixtures/oaspec.yaml --mode=client
      The status should be success
      The output should include 'Successfully generated'
      The path "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should be file
      The path "$TEST_OUTPUT_DIR/api" should not be exist
    End
  End

  # -------------------------------------------------------------------
  # Unsupported feature validation
  # -------------------------------------------------------------------

  # deepObject and multipart/form-data remain unsupported for server
  # generation, but client-only generation should still succeed.
  Describe 'client mode filters server-only validation errors'
    It 'generates successfully for specs with deepObject and inline oneOf'
      clean_test_output
      When run generate --config=test/fixtures/broken-oaspec.yaml --mode=client
      The status should be success
      The output should include 'Successfully generated'
      The path "$TEST_OUTPUT_DIR_CLIENT/api/client.gleam" should be file
      The path "$TEST_OUTPUT_DIR/api" should not be exist
    End
  End

  # -------------------------------------------------------------------
  # Complex supported spec (inline objects, oneOf $ref, allOf, enums)
  # -------------------------------------------------------------------

  Describe 'complex supported spec'
    BeforeAll 'clean_test_output'

    It 'generates successfully'
      When run generate --config=test/fixtures/complex-supported-oaspec.yaml
      The status should be success
      The output should include 'Successfully generated'
    End
  End

  Describe 'complex supported spec content'
    BeforeAll 'generate_complex_supported_once'

    # Inline enum types

    It 'generates inline enum for User.type'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type UserType {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'UserTypeAdmin'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'UserTypeRegular'
    End

    It 'generates inline enum for Filter.op'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type FilterOp {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'FilterOpEq'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'FilterOpNe'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'FilterOpGt'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'FilterOpLt'
    End

    It 'references inline enum type in Filter.op field'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'op: FilterOp'
    End

    # Inline object in response

    It 'generates anonymous type for inline response object'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type PostSearchResponseOk {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'results: Option(List(User))'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'total: Option(Int)'
    End

    # oneOf with $ref in response

    It 'generates oneOf type with $ref variants'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type GetUserResponseOk {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'GetUserResponseOkAdminUser(AdminUser)'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'GetUserResponseOkRegularUser(RegularUser)'
    End

    # allOf merged requestBody

    It 'generates merged allOf type for request body'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'pub type PostSearchRequest {'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'page: Option(Int)'
      The contents of file "$TEST_OUTPUT_DIR/api/types.gleam" should include 'query: Option(String)'
    End

    # Response types reference anonymous types

    It 'response types reference anonymous types correctly'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'PostSearchResponseOk(types.PostSearchResponseOk)'
      The contents of file "$TEST_OUTPUT_DIR/api/response_types.gleam" should include 'GetUserResponseOk(types.GetUserResponseOk)'
    End

    # Request types reference merged allOf type

    It 'request types reference merged allOf body type (optional since required defaults to false)'
      The contents of file "$TEST_OUTPUT_DIR/api/request_types.gleam" should include 'body: Option(types.PostSearchRequest)'
    End
  End
End

# ===================================================================
# Validate subcommand tests
# ===================================================================

Describe 'oaspec validate'
  Include "$SHELLSPEC_SPECDIR/spec_helper.sh"

  Describe 'CLI help'
    It 'shows usage when called with --help'
      When run validate_spec --help
      The status should be success
      The output should include 'validate'
      The output should include 'config'
    End
  End

  Describe 'successful validation'
    It 'validates a valid spec without generating files'
      clean_test_output
      When run validate_spec --config=test/fixtures/oaspec.yaml
      The status should be success
      The output should include 'Validation passed'
      The output should not include 'Generated'
      The output should not include 'Successfully generated'
    End

    It 'does not write any files'
      clean_test_output
      When run validate_spec --config=test/fixtures/oaspec.yaml
      The status should be success
      The output should not include 'Generated:'
    End
  End

  Describe 'error handling'
    It 'exits with error when config file does not exist'
      When run validate_spec --config=nonexistent.yaml
      The status should be failure
      The output should include 'Error'
    End
  End
End

# ===================================================================
# generate --check tests
# ===================================================================

Describe 'oaspec generate --check'
  Include "$SHELLSPEC_SPECDIR/spec_helper.sh"

  Describe 'when output matches'
    setup() { clean_test_output; generate --config=test/fixtures/oaspec.yaml >/dev/null 2>&1 || true; }
    Before 'setup'

    It 'passes when generated code matches existing files'
      When run generate --config=test/fixtures/oaspec.yaml --check
      The status should be success
      The output should include 'check passed'
    End
  End

  Describe 'when output does not exist'
    Before 'clean_test_output'

    It 'fails when output files do not exist'
      When run generate --config=test/fixtures/oaspec.yaml --check
      The status should be failure
      The output should include 'out of date'
    End
  End
End

# ===================================================================
# generate --fail-on-warnings tests
# ===================================================================

Describe 'oaspec generate --fail-on-warnings'
  Include "$SHELLSPEC_SPECDIR/spec_helper.sh"

  Describe 'with a clean spec'
    It 'succeeds when there are no warnings'
      clean_test_output
      When run generate --config=test/fixtures/oaspec.yaml --fail-on-warnings
      The status should be success
      The output should include 'Successfully generated'
    End
  End

  Describe 'with a spec that has warnings'
    It 'fails when warnings are present'
      clean_test_output
      When run generate --config=test/fixtures/oaspec-with-warnings.yaml --fail-on-warnings
      The status should be failure
      The output should include 'Warnings:'
      The output should include '--fail-on-warnings is set'
    End
  End
End
