#!/bin/sh
# mise_bootstrap.sh -- Shared helper that makes mise-managed tools
# (erlang, gleam, rebar) visible on PATH without requiring the caller
# to have run `mise activate` in the current shell.
#
# Usage:
#   . scripts/lib/mise_bootstrap.sh   # source from any bash/sh script
#   oaspec_require_tool gleam         # fail fast with a setup message
#
# The sourcing itself runs `oaspec_mise_bootstrap` once, so most
# callers only need the `.` line. The helper is idempotent -- sourcing
# it twice leaves PATH unchanged. Intentionally POSIX-compatible (no
# `local`, no `[[ ]]`), so it can be sourced from `sh -cu` as well as
# bash.

_oaspec_mise_prepend() {
  # Prepend $1 to PATH unless it is already present.
  case ":${PATH-}:" in
    *":$1:"*) ;;
    *) PATH="$1${PATH:+:$PATH}" ;;
  esac
}

# Tools whose parent directory should be added to PATH. `escript` and
# `erl` come with erlang but need to be reachable directly, because
# escripts generated by gleescript use `#!/usr/bin/env escript` and
# resolve the interpreter through PATH, not through mise shims.
_OASPEC_MISE_TOOLS="gleam escript erl rebar3"

oaspec_mise_bootstrap() {
  # ~/.local/bin is the canonical install dir for developer tools
  # that are not managed by mise (e.g. ShellSpec). Keep it on PATH
  # independently of the mise-managed toolchain probe below.
  if [ -n "${HOME:-}" ] && [ -d "$HOME/.local/bin" ]; then
    _oaspec_mise_prepend "$HOME/.local/bin"
  fi

  # Resolve the mise-managed toolchain to its concrete install
  # directories and add those to PATH. Doing this unconditionally
  # (even when shims are already on PATH) ensures that escript/erl
  # shebangs resolve to the real binaries rather than shims, which
  # fail with "No version is set" when invoked from a directory
  # outside the mise project where the activation env is not in scope.
  if command -v mise >/dev/null 2>&1; then
    for _oaspec_bootstrap_tool in $_OASPEC_MISE_TOOLS; do
      _oaspec_bootstrap_path="$(mise which "$_oaspec_bootstrap_tool" 2>/dev/null || true)"
      if [ -n "$_oaspec_bootstrap_path" ]; then
        _oaspec_mise_prepend "$(dirname "$_oaspec_bootstrap_path")"
      fi
    done
    unset _oaspec_bootstrap_tool _oaspec_bootstrap_path
  fi

  # Fallback: the canonical shim directory. Used when `mise` itself
  # is not on PATH (e.g. a non-standard install) or when `mise which`
  # could not resolve the tools above.
  if ! command -v gleam >/dev/null 2>&1 && [ -n "${HOME:-}" ]; then
    _oaspec_mise_prepend "$HOME/.local/share/mise/shims"
  fi

  export PATH
}

oaspec_require_tool() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0
  fi
  cat >&2 <<EOF
error: required tool '$1' was not found on PATH.

This repository manages its toolchain (Erlang, Gleam, rebar3) with
mise. To set up the development environment from a fresh checkout:

    mise install

If mise itself is missing, see https://mise.jdx.dev/getting-started.html.
Alternatively, install '$1' by hand and make sure it is on PATH
before running this command.
EOF
  return 127
}

oaspec_mise_bootstrap
