#!/usr/bin/env bash
# check_readme_examples.sh — Verify that the Gleam code snippets in
# doc/library-api.md compile against the current public API.
# Exit 1 if any snippet fails to type-check.
#
# Issue #410: previously the script hardcoded a separately-maintained
# copy of the README snippet. The hardcoded copy drifted (paths in
# particular) so the check silently stopped reflecting the doc it
# claimed to validate. This implementation extracts the snippets out
# of the markdown source at runtime via awk so the two cannot drift
# again. The library-API content moved out of README.md into
# doc/library-api.md when the README was slimmed down for usability.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/mise_bootstrap.sh
. "$SCRIPT_DIR/lib/mise_bootstrap.sh"
oaspec_require_tool gleam

cd "$(git rev-parse --show-toplevel)"

DOC_FILE="doc/library-api.md"
SMOKE_FILE="test/readme_smoke_test_.gleam"
TMP_PREFIX="$(mktemp -d)"
GENERATE_BLOCK="$TMP_PREFIX/generate.gleam"
VALIDATE_BLOCK="$TMP_PREFIX/validate.gleam"

cleanup() {
  rm -f "$SMOKE_FILE"
  rm -rf "$TMP_PREFIX"
}
trap cleanup EXIT

# Extract a fenced ```gleam block following a specific level-2 heading
# in doc/library-api.md. The doc structure is stable enough that tying
# the extraction to the heading text is safer than tracking block
# index numbers.
extract_block() {
  local heading="$1"
  local out_file="$2"

  awk -v heading="$heading" '
    BEGIN { in_section = 0; in_block = 0 }
    /^## / {
      in_section = ($0 == "## " heading)
      next
    }
    in_section && /^```gleam$/ { in_block = 1; next }
    in_section && in_block && /^```$/ { in_block = 0; in_section = 0; exit }
    in_block { print }
  ' "$DOC_FILE" > "$out_file"

  if [ ! -s "$out_file" ]; then
    echo "FAILED: could not extract '$heading' block from $DOC_FILE" >&2
    echo "(check the heading text and surrounding fenced gleam block)" >&2
    exit 1
  fi
}

extract_block "Example: generate files from a parsed spec" "$GENERATE_BLOCK"
extract_block "Example: validate without generating" "$VALIDATE_BLOCK"

# The README's second example references `spec` and `cfg` from the
# first example without redefining them — it reads as a tutorial
# continuation. Reuse the first block's setup verbatim before the
# second block so the smoke file type-checks as a self-contained module.

# Strip the imports out of the extracted blocks (they're added once at
# the top of the smoke module), leaving only the executable lines.
strip_imports() {
  grep -v '^import ' "$1" || true
}

GEN_BODY="$(strip_imports "$GENERATE_BLOCK")"
VAL_BODY="$(strip_imports "$VALIDATE_BLOCK")"

# Rewrite README comment placeholders in the second block (`// spec is
# valid; ...` and `// spec has errors`) to legal Gleam right-hand sides.
# The README uses them as prose annotations after `->`, but a real
# module needs `Nil` (or any expression). Map both arms to Nil.
VAL_BODY_FIXED="$(printf '%s\n' "$VAL_BODY" \
  | sed -E 's|->[[:space:]]*//.*|-> Nil|')"

# The README's first block also uses prose comments inside its case
# arms (`// summary.files: ...`). Those compile as no-op comments
# inside `{ ... }` blocks already, so leave them alone.

{
  cat <<'EOF'
// Auto-generated by scripts/check_readme_examples.sh — DO NOT EDIT.
// Extracted from doc/library-api.md's Example blocks (Issue #410).

import oaspec/config
import oaspec/generate
import oaspec/openapi/parser

pub fn readme_generate_example() -> Nil {
EOF
  printf '%s\n' "$GEN_BODY"
  cat <<'EOF'
  Nil
}

pub fn readme_validate_example() -> Nil {
EOF
  # Re-emit the first block's setup so `spec` and `cfg` are in scope
  # for the second block; then append the second block.
  printf '%s\n' "$GEN_BODY" | sed -n '/^[[:space:]]*let /,/^[[:space:]]*)/p'
  printf '%s\n' "$VAL_BODY_FIXED"
  cat <<'EOF'
  Nil
}
EOF
} > "$SMOKE_FILE"

echo "==> Type-checking doc/library-api.md examples..."

if gleam check; then
  echo "==> doc/library-api.md examples compile successfully."
else
  echo "FAILED: doc/library-api.md examples do not compile."
  echo "Update the code snippets in doc/library-api.md to match"
  echo "the current public API."
  echo
  echo "Generated smoke file (kept until next successful run):"
  echo "  $SMOKE_FILE"
  exit 1
fi
