#!/usr/bin/env bash
# check_readme_examples.sh — Verify that the Gleam code snippets in the
# README's "Library API" section compile against the current public API.
# Exit 1 if any snippet fails to type-check.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/mise_bootstrap.sh
. "$SCRIPT_DIR/lib/mise_bootstrap.sh"
oaspec_require_tool gleam

SMOKE_FILE="test/readme_smoke_test_.gleam"

cleanup() { rm -f "$SMOKE_FILE"; }
trap cleanup EXIT

# Extract the two library-usage code blocks from the README and wrap them
# in a compilable module.  We only need `gleam check` (type-check), not
# `gleam test`, so the function never runs.
cat > "$SMOKE_FILE" <<'GLEAM'
// Auto-generated by scripts/check_readme_examples.sh — DO NOT EDIT.
// This file verifies that the README "Library API" examples compile.

import oaspec/config
import oaspec/generate
import oaspec/openapi/parser

pub fn readme_generate_example() -> Nil {
  let assert Ok(spec) = parser.parse_file("openapi.yaml")
  let cfg = config.new(
    input: "openapi.yaml",
    output_server: "./gen/my_api",
    output_client: "./gen_client/my_api",
    package: "my_api",
    mode: config.Both,
    validate: False,
  )

  case generate.generate(spec, cfg) {
    Ok(summary) -> {
      let _ = summary.files
      let _ = summary.warnings
      let _ = summary.spec_title
      Nil
    }
    Error(generate.ValidationErrors(errors:)) -> {
      let _ = errors
      Nil
    }
  }
}

pub fn readme_validate_example() -> Nil {
  let assert Ok(spec) = parser.parse_file("openapi.yaml")
  let cfg = config.new(
    input: "openapi.yaml",
    output_server: "./gen/my_api",
    output_client: "./gen_client/my_api",
    package: "my_api",
    mode: config.Both,
    validate: False,
  )

  case generate.validate_only(spec, cfg) {
    Ok(_summary) -> Nil
    Error(generate.ValidationErrors(errors:)) -> {
      let _ = errors
      Nil
    }
  }
}
GLEAM

echo "==> Type-checking README library examples..."

if gleam check; then
  echo "==> README library examples compile successfully."
else
  echo "FAILED: README library examples do not compile."
  echo "Update the code snippets in README.md's 'Library API' section"
  echo "to match the current public API."
  exit 1
fi
