// Code generated by oaspec v0.9.0. DO NOT EDIT.

import gleam/option.{type Option}
import api/types

pub type PostSearchRequest {
  PostSearchRequest(
    body: Option(types.PostSearchRequest)
  )
}

pub type GetUserRequest {
  GetUserRequest(
    user_id: String
  )
}

pub type PostWebhookRequest {
  PostWebhookRequest(
    body: Option(types.WebhookEvent)
  )
}

