// Code generated by oaspec v0.11.0. DO NOT EDIT.

import api/types
import gleam/option.{type Option}

pub type PostSearchRequest {
  PostSearchRequest(body: Option(types.PostSearchRequest))
}

pub type GetUserRequest {
  GetUserRequest(user_id: String)
}

pub type PostWebhookRequest {
  PostWebhookRequest(body: Option(types.WebhookEvent))
}
