// Code generated by oaspec v0.15.0. DO NOT EDIT.

import api/types

pub type PostSearchResponse {
  PostSearchResponseOk(types.PostSearchResponseOk)
}

pub type GetUserResponse {
  GetUserResponseOk(types.GetUserResponseOk)
  GetUserResponseNotFound(types.Error)
}

pub type PostWebhookResponse {
  PostWebhookResponseOk
}
